version: '3.8'
services:
  postgres-kyc-service:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - weelink-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=weelink
    networks:
      - default
    deploy:
      restart_policy:
        condition: on-failure
volumes:
  weelink-data: