version: '3.8'
services:
  postgres-weelink:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - weelink-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=weelink
    networks:
      - default
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - .env
  weelink:
    build:
      context: .
    ports:
      - "8080:11223"
    environment:
      - DOMAIN=${DOMAIN}
      - ALIAS_LENGTH=${ALIAS_LENGTH}
    networks:
      - default
    depends_on:
      -   postgres-weelink
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - .env
volumes:
  weelink-data:
networks:
  default:
    driver: bridge